In [17]:
import numpy as np

In [18]:
data = np.array([1, 2, 3])

In [19]:
data[1]


2

In [20]:
data[0:2]

array([1, 2])

In [21]:
data[1:]


array([2, 3])

In [22]:
data[-2:]

array([2, 3])

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [24]:
print(a[a < 5])


[1 2 3 4]


In [25]:
five_up = (a >= 5)
print(a[five_up])


[ 5  6  7  8  9 10 11 12]


In [26]:
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)


[ 2  4  6  8 10 12]


In [27]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [28]:
five_up = (a > 5) | (a == 5)
print(five_up)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
