In [3]:
import numpy as np

In [4]:
#sorting the array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)
#by default sorts in ascending order
#we can specify order kind and axis by attributes



array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#cocatenating two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
e=np.concatenate((x, y), axis=0)


In [7]:
#gives the size of the given array
#simply the number of elements in the given array
e.size

6

In [8]:
# Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.
a = np.arange(6)
b = a.reshape(3, 2)


In [9]:
arr=np.array([[1,2,3],[4,5,6]])

In [10]:
print(arr*arr)

[[ 1  4  9]
 [16 25 36]]


In [11]:
print(arr-arr)

[[0 0 0]
 [0 0 0]]


In [12]:
print(1/arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [13]:
print(arr**0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
