In [16]:
#importing numpy
import numpy as np

In [17]:
#arrange function creates a 1d array of element zero indexed upto n element where n is the argument passed to it.
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
# array function creates an array 
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [19]:
#print the shape of an array
print(a.shape)
#prints the datatype of array elements
print(a.dtype)
#prints the dimensions in array
print(a.ndim)

(6,)
int32
1


In [20]:
b=np.zeros(4)
b

array([0., 0., 0., 0.])

In [22]:
# a 3-d array
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:

b=np.ones(4)
print(b)

[1. 1. 1. 1.]


In [28]:
# The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!
d=np.empty(2) 
d

array([2.51530017e+137, 6.24805384e+130])

In [27]:
# even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
np.arange(2, 9, 2)


array([2, 4, 6, 8])

In [ ]:
# to create an array with values that are spaced linearly in a specified interval:
np.linspace(0, 10, num=5)


In [29]:
# While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword
x = np.ones(2, dtype=np.int64)
x


array([1, 1], dtype=int64)