In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
a[2]

array([7, 8, 9])

In [6]:
print(a[2][1])
#or
print(a[2,1])
#are same

8
8


In [7]:
#3d arrays in numpy
arr3d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [8]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
old_value=arr3d[0].copy()
old_value

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [14]:
arr3d=old_value
arr3d

array([[1, 2, 3],
       [4, 5, 6]])