In [1]:
import numpy as np

In [2]:
data = np.array([1, 2, 3])

In [3]:
data[1]


2

In [4]:
data[0:2]

array([1, 2])

In [5]:
data[1:]


array([2, 3])

In [6]:
data[-2:]

array([2, 3])

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [8]:
print(a[a < 5])


[1 2 3 4]


In [9]:
five_up = (a >= 5)
print(a[five_up])


[ 5  6  7  8  9 10 11 12]


In [10]:
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)


[ 2  4  6  8 10 12]


In [11]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [12]:
five_up = (a > 5) | (a == 5)
print(five_up)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [15]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [24]:
#broadcasting the value
arr[5:8]=12
print(arr)
#now if again the values are sliced and saved in new variable
arr_slice=arr[5:8]
print(arr_slice)
#when value of the new array is changed the original array value also changes this is known as boadcasting
#below slice is known as bare slice
arr_slice[:]=64
print(arr)
#surprised yes you must be when you are moving from any other programming language to python's numpy but this all is due to very large arrays that are numpy imagine if we need to copy the array each time than how much time is wasted.

[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[ 0  1  2  3  4 64 64 64  8  9]


In [27]:
#to copy the array explicitly instead of viewing you will need to copy it using copy functions
arr_copy=arr[5:8].copy()
#changing element in copied array does not affect the original array
arr_copy[:]=18
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])