In [1]:
import numpy as np

# Create a NumPy array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


In [2]:
import numpy as np

# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

# Create a 3x2 array filled with ones
ones_array = np.ones((3, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
import numpy as np

# Create an empty array with 2 rows and 2 columns
empty_array = np.empty((2, 2))
print(empty_array)


[[0.00000000e+000 8.49189763e-312]
 [8.49189763e-312 8.49189763e-312]]


In [5]:
import numpy as np

# Create an array with values from 0 to 9 (10 values)
range_array = np.arange(10)
print(range_array)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np

# Create an array with 5 evenly spaced values from 0 to 1
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)


[0.   0.25 0.5  0.75 1.  ]


In [8]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)
identity_matrix = np.identity(4)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
shape = arr.shape
print(shape)  # Output: (2, 3)


(2, 3)


In [10]:
import numpy as np

# Create a 2x4 array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Get the total number of elements in the array
size = arr.size
print(size)  # Output: 8


8


In [11]:
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(12)

# Reshape it into a 3x4 matrix
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
import numpy as np

# Create an array
arr = np.array([10, 20, 30, 40, 50])

# Calculate the mean of the elements
mean = np.mean(arr)
print(mean)  # Output: 30.0


30.0


In [13]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the sum of the elements
total = np.sum(arr)
print(total)  # Output: 15


15


In [14]:
import numpy as np

# Create an array
arr = np.array([7, 2, 9, 1, 5, 8, 4])

# Find the minimum and maximum values
minimum = np.min(arr)
maximum = np.max(arr)

print("Minimum:", minimum)  # Output: 1
print("Maximum:", maximum)  # Output: 9


Minimum: 1
Maximum: 9


In [15]:
import numpy as np

# Create an array
arr = np.array([7, 2, 9, 1, 5, 8, 4])

# Find the indices of the minimum and maximum values
min_index = np.argmin(arr)
max_index = np.argmax(arr)

print("Index of Minimum:", min_index)  # Output: 3
print("Index of Maximum:", max_index)  # Output: 2


Index of Minimum: 3
Index of Maximum: 2


In [16]:
import numpy as np

# Create an array
arr = np.array([12, 22, 32, 42, 52])

# Calculate the standard deviation
std_dev = np.std(arr)
print(std_dev)  # Output: 15.8114


14.142135623730951


In [17]:
import numpy as np

# Create an array
arr = np.array([12, 22, 32, 42, 52])

# Calculate the variance
variance = np.var(arr)
print(variance)  # Output: 250.0


200.0


In [18]:
import numpy as np

# Create an unsorted array
arr = np.array([9, 1, 6, 3, 8, 2, 5, 4, 7])

# Sort the array
sorted_arr = np.sort(arr)
print(sorted_arr)


[1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate them along the 0th axis (rows)
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)


[1 2 3 4 5 6]
